version: '3.8'

services:
  api:
    build: ./api
    container_name: event-planning-api
    ports:
      - "8800:8800"
    environment:
      -
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: always
    networks:
      - event-planning-network

  client:
    build: ./client
    container_name: event-planning-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8800
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
    networks:
      - event-planning-network

networks:
  event-planning-network:
    driver: bridge