version: '3.8'

services:
  api:
    build: ./api
    container_name: event-planning-api
    ports:
      - "8800:8800"
    environment:
      - DATABASE_URL=mongodb+srv://s3991730:mkhoi.1909@vmkhoicluster.kawro.mongodb.net/event_management_app?retryWrites=true&w=majority&appName=vmkhoiCluster
      - JWT_SECRET=Way4dg+DrRv9JHzJUijTtEIzLCyR0Ud0dLJtbaCRgdk=
      - CLIENT_URL=http://localhost:5173
      - CLOUDINARY_CLOUD_NAME=dtc1fgnvp
      - CLOUDINARY_UPLOAD_PRESET=ml_default
      - EMAIL_USERNAME=tantaitruong2611@gmail.com
      - EMAIL_PASSWORD=kmnl zomj bpio wphx
      - EMAIL_FROM_NAME=Event Management App
      - EMAIL_FROM_ADDRESS=tantaitruong2611@gmail.com
      - REQUIRE_EMAIL_VERIFICATION=false
      - default_username=admin
      - default_password=admin123
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: always
    networks:
      - event-planning-network

  client:
    build: ./client
    container_name: event-planning-client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8800
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: always
    networks:
      - event-planning-network

networks:
  event-planning-network:
    driver: bridge