version: '3.8'


services:
  
  api:
    build: ./api
    container_name: api
    ports:
      - "8800:8800"
    env_file:
      - /api/.env
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules  
    networks:
      - event-planning-network

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8800
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
    networks:
      - event-planning-network

networks:
  event-planning-network:
    driver: bridge